// web/src/lib/components/FirstChapterDialog.svelte
<script lang="ts">
	import Dialog from './Dialog.svelte';
	import { setFirstChapter } from '$api/translation';
	import { ManualExtractCancelled } from '$stores/manualExtract.svelte';

	interface Props {
		open: boolean;
		novelId: string;
		novelUrl: string;
		onclose: () => void;
		onsuccess: (chapterNumber: number) => void;
	}

	let { open, novelId, novelUrl, onclose, onsuccess }: Props = $props();

	let url = $state('');
	let submitting = $state(false);
	let error = $state('');

	const host = $derived.by(() => {
		try {
			return new URL(novelUrl).host;
		} catch {
			return '';
		}
	});

	async function submit(event: SubmitEvent) {
		event.preventDefault();
		error = '';

		const candidate = url.trim();
		if (!candidate) {
			error = 'Paste the URL of the first chapter.';
			return;
		}
		if (host && !candidate.includes(host)) {
			error = `That link is not on ${host}, which is where this novel lives.`;
			return;
		}

		submitting = true;
		try {
			const chapter = await setFirstChapter(novelId, candidate);
			url = '';
			onsuccess(chapter.number ?? 1);
		} catch (cause) {
			error =
				cause instanceof ManualExtractCancelled
					? 'Cancelled. The first chapter was not set.'
					: cause instanceof Error
						? cause.message
						: 'Could not translate that chapter.';
		} finally {
			submitting = false;
		}
	}
</script>

<Dialog
	{open}
	title="Set the first chapter"
	description="Later chapters are discovered from this one, so it only needs doing once."
	onclose={submitting ? () => {} : onclose}
>
	<form id="first-chapter" onsubmit={submit}>
		<div class="field">
			<label for="first-chapter-url">First chapter URL</label>
			<input
				id="first-chapter-url"
				class="input"
				type="url"
				inputmode="url"
				autocomplete="off"
				spellcheck="false"
				placeholder={host ? `https://${host}/...` : 'https://example.com/novel/1/chapter/1'}
				bind:value={url}
				disabled={submitting}
			/>
			{#if error}
				<p class="error" role="alert">{error}</p>
			{:else}
				<p class="hint">This chapter is translated straight away so you can start reading.</p>
			{/if}
		</div>
	</form>

	{#snippet footer()}
		<button class="btn" onclick={onclose} disabled={submitting}>Cancel</button>
		<button class="btn btn--primary" type="submit" form="first-chapter" disabled={submitting}>
			{submitting ? 'Translating…' : 'Translate it'}
		</button>
	{/snippet}
</Dialog>

// src/components/FirstChapterDialog.tsx
import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/components/ui/use-toast';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { setFirstChapterUrl } from '../services/translationService';

interface FirstChapterDialogProps {
  novelId: string;
  isOpen: boolean;
  novelUrl: string;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

const FirstChapterDialog = ({ novelId, isOpen, novelUrl, onOpenChange, onSuccess }: FirstChapterDialogProps) => {
  const [url, setUrl] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!url.trim() || !url.includes(novelUrl.split('/')[2])) {
      toast({
        title: "Error",
        description: "Please enter a valid URL",
        variant: "destructive",
      });
      return;
    }
    
    setIsSubmitting(true);
    
    try {
      const toastId = toast({
        title: "Setting first chapter URL",
      }).id;
      
      const firstChapter = await setFirstChapterUrl(novelId, url);
      
      toast({
        title: "Success",
        description: "First chapter URL set and chapter translated successfully. You can now start reading."
      });
      
      setUrl('');
      onOpenChange(false);
      onSuccess();
    } catch (error) {
      console.error('Error setting first chapter URL:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      toast({
        title: "Error",
        description: `Failed to set first chapter URL: ${errorMessage}`,
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Set First Chapter URL</DialogTitle>
          <DialogDescription>
            Enter the URL of the first chapter to enable sequential reading.
            <br />
            For example: https://www.69shuba.com/txt/84522/39367190
          </DialogDescription>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="chapterUrl">Chapter URL</Label>
            <Input
              id="chapterUrl"
              placeholder="https://example.com/novel/12345/chapter/1"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              required
            />
            <p className="text-xs text-muted-foreground">
              Enter the complete URL to the first chapter of the novel.
              The links of subsequent chapters will be parsed from here.
            </p>
          </div>
          
          <DialogFooter className="sm:justify-between">
            <DialogClose asChild>
              <Button type="button" variant="outline" disabled={isSubmitting}>
                Cancel
              </Button>
            </DialogClose>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? 'Setting...' : 'Set First Chapter'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default FirstChapterDialog;
